export const adminSettings = {
  metaTitle: "Ajustes",
  eyebrow: "Ajustes",
  title: "Datos del sitio",
  description: "Textos del hero, bio, disponibilidad y datos de contacto.",
  saved: "Ajustes guardados.",

  sections: {
    hero: "Hero",
    bio: "Sobre mí",
    availability: "Disponibilidad",
    contact: "Contacto y redes",
    cv: "CV en PDF",
  },

  fields: {
    nombre: "Nombre completo",
    tagline: "Tagline",
    taglineHint: "Aparece bajo el nombre en el hero de terminal.",
    hero_descripcion: "Descripción del hero",
    bio: "Bio",
    disponible_freelance: "Disponible para proyectos freelance",
    disponible_practica: "Disponible para práctica profesional",
    practica_desde: "Práctica desde",
    practica_duracion: "Duración de la práctica",
    practica_duracionPlaceholder: "360 horas / 3 meses",
    email: "Correo de contacto",
    emailHint: "También recibe los avisos del formulario de contacto.",
    whatsapp: "WhatsApp",
    whatsappHint: "Con código de país, sin + ni espacios. Ej: 56912345678",
    github_url: "GitHub",
    linkedin_url: "LinkedIn",
  },

  cv: {
    current: "CV actual",
    none: "Todavía no hay un CV subido.",
    view: "Ver PDF",
    upload: "Subir CV",
    replace: "Reemplazar CV",
    remove: "Quitar CV",
    uploading: "Subiendo…",
    hint: "PDF · máx. 10 MB. Se reemplaza el anterior y el link público no cambia.",
    invalidType: "El CV debe ser un PDF.",
    uploaded: "CV actualizado.",
    removed: "CV quitado.",
    removeConfirmTitle: "¿Quitar el CV?",
    removeConfirmBody: "El botón de descarga dejará de aparecer en el sitio.",
  },
} as const;
