/** Textos de las secciones de contenido del backoffice (Fase 5). */

const common = {
  add: "Agregar",
  edit: "Editar",
  delete: "Borrar",
  published: "Publicado",
  draft: "Borrador",
  moveUp: (label: string) => `Subir ${label}`,
  moveDown: (label: string) => `Bajar ${label}`,
  togglePublished: (label: string) => `Publicar ${label}`,
  deleteTitle: (label: string) => `¿Borrar “${label}”?`,
  deleteBody: "Esta acción no se puede deshacer.",
  moved: "Orden actualizado.",
} as const;

export const adminContent = {
  common,

  services: {
    metaTitle: "Servicios",
    eyebrow: "Servicios",
    title: "Servicios",
    description: "Lo que ofreces, en lenguaje de cliente. El orden aquí es el orden en el sitio.",
    newItem: "Nuevo servicio",
    newTitle: "Nuevo servicio",
    editTitle: "Editar servicio",
    empty: "Todavía no hay servicios.",
    fields: {
      titulo: "Título",
      descripcion: "Descripción",
      icono: "Ícono",
      iconoNone: "Sin ícono",
      iconoSearch: "Buscar ícono",
      iconoEmpty: "No hay íconos con ese nombre.",
      publicado: "Publicado",
    },
    toasts: {
      created: "Servicio creado.",
      saved: "Servicio guardado.",
      published: "Servicio publicado.",
      unpublished: "Servicio pasado a borrador.",
      deleted: "Servicio borrado.",
    },
  },

  testimonials: {
    metaTitle: "Testimonios",
    eyebrow: "Testimonios",
    title: "Testimonios",
    description: "Opiniones de clientes y compañeros. Puedes asociarlas a un proyecto.",
    newItem: "Nuevo testimonio",
    newTitle: "Nuevo testimonio",
    editTitle: "Editar testimonio",
    empty: "Todavía no hay testimonios.",
    noProject: "Sin proyecto",
    draftProject: "(borrador)",
    fields: {
      autor: "Autor",
      cargo: "Cargo o relación",
      texto: "Testimonio",
      project_id: "Proyecto asociado",
      publicado: "Publicado",
    },
    toasts: {
      created: "Testimonio creado.",
      saved: "Testimonio guardado.",
      published: "Testimonio publicado.",
      unpublished: "Testimonio pasado a borrador.",
      deleted: "Testimonio borrado.",
    },
  },

  timeline: {
    metaTitle: "Trayectoria",
    eyebrow: "Trayectoria",
    title: "Trayectoria",
    description: "Formación, experiencia, freelance y ayudantías que aparecen en el CV.",
    newItem: "Nuevo ítem",
    newTitle: "Nuevo ítem de trayectoria",
    editTitle: "Editar ítem de trayectoria",
    emptyGroup: "Sin ítems en esta sección.",
    current: "Actual",
    tipos: {
      formacion: "Formación",
      experiencia: "Experiencia",
      freelance: "Freelance",
      ayudantia: "Ayudantía",
    },
    fields: {
      tipo: "Tipo",
      titulo: "Título o cargo",
      organizacion: "Organización",
      inicio: "Inicio",
      fin: "Fin",
      actual: "Actualmente aquí",
      descripcion: "Descripción",
    },
    toasts: {
      created: "Ítem creado.",
      saved: "Ítem guardado.",
      deleted: "Ítem borrado.",
    },
  },

  skills: {
    metaTitle: "Habilidades",
    eyebrow: "Habilidades",
    title: "Habilidades",
    description: "Tecnologías y herramientas agrupadas por área, tal como aparecen en el CV.",
    newItem: "Nueva habilidad",
    newTitle: "Nueva habilidad",
    editTitle: "Editar habilidad",
    emptyGroup: "Sin habilidades en esta área.",
    areas: {
      frontend: "Frontend",
      backend: "Backend",
      hardware: "Hardware",
      ia: "IA",
      infra: "Infraestructura",
      otras: "Otras",
    },
    fields: {
      nombre: "Nombre",
      area: "Área",
    },
    toasts: {
      created: "Habilidad creada.",
      saved: "Habilidad guardada.",
      deleted: "Habilidad borrada.",
    },
  },

  messages: {
    metaTitle: "Mensajes",
    eyebrow: "Mensajes",
    title: "Bandeja de entrada",
    description: "Mensajes del formulario de contacto, del más reciente al más antiguo.",
    empty: "No hay mensajes con estos filtros.",
    filters: {
      label: "Filtrar mensajes",
      type: "Tipo",
      status: "Estado",
      all: "Todos",
      unread: "No leídos",
    },
    tipos: {
      freelance: "Freelance",
      practica: "Práctica",
      otro: "Otro",
    },
    unreadDot: "No leído",
    markRead: "Marcar como leído",
    markUnread: "Marcar como no leído",
    reply: "Responder por correo",
    replySubject: "Re: tu mensaje en martodev",
    back: "Volver a la bandeja",
    receivedAt: "Recibido",
    pagination: {
      label: "Paginación",
      previous: "Anterior",
      next: "Siguiente",
      page: (page: number, total: number) => `Página ${page} de ${total}`,
    },
    deleteTitle: "¿Borrar este mensaje?",
    deleteBody: "Esta acción no se puede deshacer.",
    toasts: {
      read: "Marcado como leído.",
      unread: "Marcado como no leído.",
      deleted: "Mensaje borrado.",
    },
  },
} as const;
