export const adminProjects = {
  metaTitle: "Proyectos",
  eyebrow: "Proyectos",
  title: "Proyectos",
  description: "Casos de estudio del portafolio. El orden aquí es el orden en el sitio.",
  newProject: "Nuevo proyecto",
  empty: "Todavía no hay proyectos.",

  categorias: {
    cliente: "Cliente",
    propio: "Propio",
    academico: "Académico",
  },

  list: {
    headers: {
      order: "Orden",
      project: "Proyecto",
      category: "Categoría",
      published: "Publicado",
      featured: "Destacado",
      actions: "Acciones",
    },
    published: "Publicado",
    draft: "Borrador",
    featured: "Destacado",
    moveUp: (title: string) => `Subir ${title}`,
    moveDown: (title: string) => `Bajar ${title}`,
    edit: "Editar",
    delete: "Borrar",
    togglePublished: (title: string) => `Publicar ${title}`,
    toggleFeatured: (title: string) => `Destacar ${title}`,
  },

  toasts: {
    created: "Proyecto creado.",
    saved: "Proyecto guardado.",
    published: "Proyecto publicado.",
    unpublished: "Proyecto pasado a borrador.",
    featured: "Proyecto marcado como destacado.",
    unfeatured: "Proyecto quitado de destacados.",
    moved: "Orden actualizado.",
    deleted: "Proyecto borrado.",
    deletedFilesWarning: "Proyecto borrado, pero algunas imágenes no se pudieron quitar del Storage.",
  },

  deleteConfirm: {
    title: (name: string) => `¿Borrar “${name}”?`,
    body: "Se borrará el proyecto y todas sus imágenes. Esta acción no se puede deshacer.",
  },

  form: {
    newTitle: "Nuevo proyecto",
    editTitle: "Editar proyecto",
    back: "Volver a proyectos",
    viewPublic: "Ver en el sitio",
    sections: {
      basics: "Datos principales",
      caseStudy: "Caso de estudio",
      content: "Detalle técnico",
      media: "Imágenes",
      links: "Stack y enlaces",
      visibility: "Visibilidad",
    },
    fields: {
      titulo: "Título",
      slug: "Slug",
      slugHint: "Parte final de la URL: /proyectos/",
      resumen: "Resumen",
      resumenHint: "1–2 líneas para las tarjetas.",
      categoria: "Categoría",
      cliente: "Cliente",
      rol: "Qué construí y mi rol",
      problema: "Problema",
      resultado: "Resultado",
      contenido: "Detalle técnico",
      portada: "Portada",
      portadaHint: "Se usa en tarjetas y como imagen al compartir. Idealmente 1200×630.",
      galeria: "Galería",
      stack: "Stack",
      demo_url: "URL de la demo",
      repo_url: "URL del repositorio",
      publicado: "Publicado",
      publicadoHint: "Visible en el sitio público.",
      destacado: "Destacado",
      destacadoHint: "Aparece en la portada (se recomiendan 3–4).",
    },
    coverAlt: "Portada del proyecto",
    galleryAlt: (n: number) => `Imagen ${n} de la galería`,
  },
} as const;
