/** Textos compartidos por formularios y componentes del backoffice. */
export const adminForms = {
  save: "Guardar cambios",
  saving: "Guardando…",
  cancel: "Cancelar",
  optional: "opcional",
  genericError: "No se pudo guardar. Revisa los campos marcados.",
  unexpectedError: "Ocurrió un error inesperado. Intenta de nuevo.",
  notFound: "No se encontró el elemento. Puede que ya se haya borrado.",
  toastClose: "Cerrar aviso",

  validation: {
    required: "Este campo es obligatorio.",
    tooLong: (max: number) => `Máximo ${max} caracteres.`,
    email: "Ingresa un correo válido.",
    url: "Ingresa una URL válida que empiece con https://",
    date: "Ingresa una fecha válida.",
    whatsapp: "Solo números, con código de país. Ej: 56912345678",
    slug: "Solo minúsculas, números y guiones. Ej: mi-proyecto",
    slugTaken: "Ya existe un proyecto con este slug.",
    stackItem: "Cada tecnología debe tener entre 1 y 40 caracteres.",
    stackMax: "Máximo 30 tecnologías.",
    galleryMax: "Máximo 20 imágenes en la galería.",
    invalidPath: "Ruta de imagen inválida.",
    invalidDoc: "El contenido del editor no es válido.",
    endBeforeStart: "La fecha de fin no puede ser anterior a la de inicio.",
  },

  upload: {
    choose: "Subir imagen",
    replace: "Reemplazar",
    remove: "Quitar",
    uploading: "Subiendo…",
    add: "Agregar imágenes",
    invalidType: "Formato no permitido. Usa JPG, PNG, WebP o AVIF.",
    tooLarge: (mb: number) => `El archivo supera ${mb} MB.`,
    failed: "No se pudo subir el archivo.",
    moveLeft: "Mover a la izquierda",
    moveRight: "Mover a la derecha",
    removeImage: (n: number) => `Quitar imagen ${n}`,
    hint: "JPG, PNG, WebP o AVIF · máx. 5 MB",
  },

  tags: {
    placeholder: "Escribe y presiona Enter",
    remove: (tag: string) => `Quitar ${tag}`,
    hint: "Enter o coma para agregar. Retroceso borra la última.",
  },

  editor: {
    toolbar: "Formato de texto",
    paragraph: "Párrafo",
    h2: "Título 2",
    h3: "Título 3",
    h4: "Título 4",
    bold: "Negrita",
    italic: "Cursiva",
    code: "Código en línea",
    bulletList: "Lista con viñetas",
    orderedList: "Lista numerada",
    blockquote: "Cita",
    codeBlock: "Bloque de código",
    link: "Enlace",
    linkPlaceholder: "https://…",
    linkApply: "Aplicar",
    linkRemove: "Quitar enlace",
    image: "Insertar imagen",
    imageAlt: "Imagen del proyecto",
    undo: "Deshacer",
    redo: "Rehacer",
    placeholder: "Escribe aquí…",
  },

  confirm: {
    confirm: "Sí, borrar",
    deleting: "Borrando…",
  },
} as const;
